# Generated by Django 3.1.2 on 2020-10-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttempsFailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_client', models.CharField(max_length=50)),
                ('host_client', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=2)),
                ('date_attempt', models.DateTimeField()),
            ],
        ),
    ]
