# Generated by Django 3.1.2 on 2020-10-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peaky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempsfailmodel',
            name='ip_client',
            field=models.CharField(max_length=500),
        ),
    ]
