# Generated by Django 3.1.2 on 2020-10-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peaky', '0002_auto_20201003_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempsfailmodel',
            name='date_attempt',
            field=models.DateTimeField(max_length=500),
        ),
    ]
