# Generated by Django 3.1.2 on 2020-10-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peaky', '0003_auto_20201003_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempsfailmodel',
            name='date_attempt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
