# Generated by Django 3.1.2 on 2020-10-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peaky', '0004_auto_20201003_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempsfailmodel',
            name='host_client',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='attempsfailmodel',
            name='ip_client',
            field=models.CharField(max_length=30),
        ),
    ]
