# Generated by Django 3.1.2 on 2020-10-04 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peaky', '0006_auto_20201004_0258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeakModel',
            new_name='Peak',
        ),
    ]
