# Generated by Django 3.1.2 on 2020-10-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peaky', '0007_auto_20201004_0347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttemptFailModel',
            new_name='AttemptFail',
        ),
    ]
